name: Continous integration

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - "*"

permissions:
  contents: read

jobs:
  check_format:
    env:
      CLANGFORMAT: clang-format-18
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 2
      - name: Install clang-format-18
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt install -y clang-format-18
      - name: Run format check
        run: bash tools/check_format.sh

  run_tests_unix:
    needs: check_format
    strategy:
      matrix:
        os:
          - ubuntu-latest
        assembler:
          - nasm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install build dependencies (Linux)
        run: sudo apt install ${{ matrix.assembler }}
        if: runner.os == 'Linux'
      - name: Build
        run: |
          ./autogen.sh
          ./configure
          bash -c 'make -j $(nproc)'
      - name: Run tests
        run: bash tools/test_checks.sh
      - name: Run extended tests
        run: bash tools/test_extended.sh
        if: runner.os == 'Linux'  # Fails on Mac OS due to nmake consistency issue

  run_tests_windows:
    needs: check_format
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set MSVC developer prompt
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
      - name: Install nasm
        uses: ilammy/setup-nasm@13cbeb366c45c4379d3478cdcbadd8295feb5028 # v1.5.1
      - name: Build
        run: nmake -f Makefile.nmake

  run_tests_linux-riscv64-v:
    needs: check_format
    runs-on: run_tests_linux-riscv64-v
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Build
        run: |
          ./autogen.sh
          ./configure
          bash -c 'make -j $(nproc)'
      - name: Run tests
        run: bash tools/test_checks.sh
      - name: Run extended tests
        run: bash tools/test_extended.sh
